C15 49 jruizz 290124
dlab-team/c15-backend pull request #13
Opened 2024-01-30 16:44 UTC by JonaRuizZ

2024-01-31 01:02 UTC, Martiixx requested changes
Hacer pull request contra la rama develop en vez de main.
Resolver conflictos desde develop

2024-02-07 01:30 UTC, JonaRuizZ commented
Había realizado una nueva PR para cambiar la rama de destino, pero con ayuda de Felipe pude editar desde la misma PR realizada la rama de destino.
Mil disculpas.

2024-02-07 11:51 UTC, Martiixx commented
Solo falta resolver el conflicto en el archivo de company.js

2024-02-07 12:54 UTC, Martiixx commented
![image](https://github.com/dlab-team/c15-backend/assets/23131106/fe2232dd-ac07-4dab-a29c-dac6d5cc883a)

2024-02-07 12:57 UTC, Martiixx commented
@JonaRuizZ haz un pull desde la rama develop hacia tu rama, en estos casos tus cambios locales deberian tener ambas modificaciones, tanto de develop como tus cambios, y luego posterior a eso actualizar el pr

2024-02-07 13:15 UTC, JonaRuizZ commented
Ok, lo haré ahora, gracias Martín.

2024-02-07 13:24 UTC, JonaRuizZ commented
Me costó un poquito mapear e identificar cual era el error que estaba cometiendo, pero lo entendí, espero se haya resuelto, gracias Martín y disculpa la molestia.

2024-02-07 13:25 UTC, JonaRuizZ commented
Me costó entender un poco el mapeo de las ramas y del problema que estaba cometiendo, pero al final creo se pudo arreglar y entendí en qué estaba fallando, gracias Martín, espero no siga teniendo problemas el código y mil disculpas.

2024-02-07 13:39 UTC, Martiixx approved these changes
Super bien.
Este tipo de casos es super común en el mundo laboral y siempre dan dolores de cabeza cuando los códigos son mas complejos, excelente trabajo resolviendo el conflicto!

2024-02-07 13:39 UTC, merged