Integración de Sequelize
dlab-team/c15-backend pull request #8
Opened 2024-01-22 20:57 UTC by Hcayupi

Realicé las everiguaciones de cómo integrar Sequelize y me llevaron al resultado que muestran los cambios de esta rama.
Para comprobar su funcionamiento creé tres tablas usando pgAdmin y Docker: Persona, Tipo empresa y Empresa. Luego creé los modelos de cada una en el proyecto, para después comenzar a hacer las pruebas creando una clase en un controlador y haciendo las llamadas desde routes.js.

2024-01-23 01:21 UTC, Martiixx requested changes
Hay que actualizar el idioma de las entidades a ingles como convención para desarrollar el proyecto, voy a dejar el PR como pendiente

2024-01-24 03:25 UTC, Hcayupi commented
Modifiqué los nombres de los modelos y fuciones a inglés, creé un nuevo archivo userRouter.js para trabajar con el userController.js.  Pienso que  facilitará la legibilidad del código. Los modelos fueron modificados siguiendo el último diseño de BD propuesto en el ticket Jira C15-19. Hice pruebas de inserción, consulta, modificación y eliminación con PostMan antes de hacer el Push y durante estas pruebas añadí  body-parser en el archivo app.js.

2024-01-24 05:45 UTC, Hcayupi commented
En el commit anterior no consideré el package.json que tiene las dependencias:pg, pg-hstore y sequelize

2024-01-24 21:26 UTC, Martiixx approved these changes

2024-01-24 21:26 UTC, merged